# Generated by Django 4.2.3 on 2023-09-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
